export enum TwCountry {
    臺北市 = 'Taipei,tw',
    新北市 = 'New Taipei,tw',
    桃園市 = 'Taoyuan,tw',
    臺中市 = 'Taichung,tw',
    臺南市 = 'Tainan,tw',
    高雄市 = 'Kaohsiung,tw',
    基隆市 = 'Keelung,tw',
    新竹市 = 'Hsinchu,tw',
    嘉義市 = 'Chiayi,tw',
    新竹縣 = 'Hsinchu,tw',
    苗栗縣 = 'Miaoli,tw',
    彰化縣 = 'Changhua,tw',
    南投縣 = 'Nantou,tw',
    雲林縣 = 'Yunlin,tw',
    嘉義縣 = 'Chiayi,tw',
    屏東縣 = 'Pingtung,tw',
    宜蘭縣 = 'Yilan,tw',
    花蓮縣 = 'Hualien,tw',
    臺東縣 = 'Taitung,tw',
    澎湖縣 = 'Penghu,tw',
    金門縣 = 'Kinmen,tw',
    連江縣 = 'Lienchiang,tw'
  }